name: Deploy To EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 클론
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./yammy_back/src/main/resources/application.yml

      - name: 테스트 및 빌드
        run: |
          cd yammy_back
          chmod +x gradlew
          ./gradlew clean build

      ########################################
      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t yammy .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag yammy ${{ steps.login-ecr.outputs.registry }}/yammy:latest
      
      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/yammy:latest
      
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            export PATH=$PATH:/usr/local/bin
            aws ecr get-login-password --region ap-northeast-2 | sudo docker login --username AWS --password-stdin 725115073641.dkr.ecr.ap-northeast-2.amazonaws.com
            sudodocker stop yammy || true
            sudo docker rm yammy || true
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/yammy:latest
            sudo docker run -d --name yammy -p 80:80 ${{ steps.login-ecr.outputs.registry }}/yammy:latest
      # 첫 줄은 도커 로그인 코드
      # 여기는 sudo 붙이면 no basic auth credentials 라고 에러 발생