name: Deploy To EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 클론
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./yammy_back/src/main/resources/application.yml

      - name: 테스트 및 빌드
        run: |
          cd yammy_back
          ./gradlew clean build

      - name: 빌드 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./yammy_project.jar

      - name: SCP에 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/yammy_project/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }} # EC2의 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 접속 username
          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            rm -rf /home/ubuntu/yammy_project/current
            mkdir /home/ubuntu/yammy_project/current
            mv /home/ubuntu/yammy_project/tobe/project.jar /home/ubuntu/yammy_project/current/project.jar
            cd /home/ubuntu/yammy_project/current
            sudo fuser -k -n tcp 80 || true
            sudo nohup java -jar project.jar > ./output.log 2>&1 &